"""Market data layer.

Scanner agents never talk to a marketplace directly — they talk to a
`DataSource`. Demo mode wires them to `SimulatedMarket`, a deterministic
world with real internal causes (supply shocks, viral spikes, restocks) that
the pipeline has to discover from the outside, exactly as it would in
production. A live deployment implements the same interface with real
adapters (see `live.py`).
"""

from typing import Protocol

from .world import SimulatedMarket  # noqa: F401


class DataSource(Protocol):
    """What every scanner/verifier is allowed to ask the outside world."""

    tick_no: int

    def product_ids(self) -> list[str]: ...
    def venue_ids(self) -> list[str]: ...
    def listings(self, venue: str) -> list[tuple[dict, dict]]: ...
    def listing(self, product_id: str, venue: str) -> dict | None: ...
    def product_history(self, product_id: str, venue: str) -> list[dict]: ...
    def product_public(self, product_id: str) -> dict: ...
    def mentions(self, entity_id: str, source: str) -> list[int]: ...
    def social_sources(self) -> list[str]: ...
    def niches(self) -> list[dict]: ...
    def niche_history(self, niche_id: str) -> list[dict]: ...
    def headlines(self, since_tick: int) -> list[dict]: ...
    def event_log(self, entity_id: str) -> list[dict]: ...
